def encode_rad(input_file: str, output_dir: str) -> None: ...
def encode_trained_rad(directory: str, output_dir: str, levels: int, moment_factor: float) -> None: ...

from collections.abc import Buffer, Sequence

class TrainedLevel:
    def __init__(self, position: Buffer, rotation: Buffer, log_scaling: Buffer,
                 alpha_logit: Buffer, sh_feature: Buffer, labels: Buffer) -> None: ...

def encode_trained_arrays(levels: Sequence[TrainedLevel], parents: Sequence[Buffer],
                          output_dir: str, moment_factor: float) -> None: ...

def encode_trained_archive(levels: Sequence[TrainedLevel], parents: Sequence[Buffer],
                           output_file: str, moment_factor: float) -> None: ...

class MergedLevel:
    def __init__(self, position: Buffer, rotation: Buffer, scales: Buffer,
                 opacity: Buffer, labels: Buffer, right_weight: Buffer) -> None: ...

def encode_merged_arrays(leaves: TrainedLevel, parents: MergedLevel, children: Buffer,
                         output_dir: str, lod_base: float) -> None: ...

def encode_merged_archive(leaves: TrainedLevel, parents: MergedLevel, children: Buffer,
                          output_file: str, lod_base: float) -> None: ...
