def encode_rad(input_file: str, output_dir: str) -> None: ...
def encode_trained_rad(directory: str, output_dir: str, levels: int, moment_factor: float, resolution_factor: float) -> None: ...

from collections.abc import Buffer, Sequence

class TrainedLevel:
    def __init__(self, position: Buffer, rotation: Buffer, log_scaling: Buffer,
                 alpha_logit: Buffer, sh_feature: Buffer, labels: Buffer) -> None: ...

def encode_trained_arrays(levels: Sequence[TrainedLevel], parents: Sequence[Buffer],
                          output_dir: str, moment_factor: float, resolution_factor: float) -> None: ...

def encode_trained_archive(levels: Sequence[TrainedLevel], parents: Sequence[Buffer],
                           output_file: str, moment_factor: float, resolution_factor: float) -> None: ...
