def encode_rad(input_file: str, output_dir: str) -> None: ...
def encode_trained_rad(directory: str, output_dir: str, levels: int, moment_factor: float) -> None: ...

from collections.abc import Buffer, Sequence
from typing import ClassVar

class TrainedLevel:
    def __init__(self, position: Buffer, rotation: Buffer, log_scaling: Buffer,
                 alpha_logit: Buffer, sh_feature: Buffer, labels: Buffer) -> None: ...

def encode_trained_arrays(levels: Sequence[TrainedLevel], parents: Sequence[Buffer],
                          output_dir: str, moment_factor: float) -> None: ...

def encode_trained_archive(levels: Sequence[TrainedLevel], parents: Sequence[Buffer],
                           output_file: str, moment_factor: float) -> None: ...

class MergedLevel:
    def __init__(self, position: Buffer, rotation: Buffer, scales: Buffer,
                 opacity: Buffer, labels: Buffer, right_weight: Buffer) -> None: ...

class Compression:
    Gz: ClassVar[Compression]
    Zstd: ClassVar[Compression]

class EncodeTimings:
    @property
    def input_seconds(self) -> float: ...
    @property
    def assemble_seconds(self) -> float: ...
    @property
    def prune_seconds(self) -> float: ...
    @property
    def chunk_seconds(self) -> float: ...
    @property
    def resolve_seconds(self) -> float: ...
    @property
    def encode_seconds(self) -> float: ...
    @property
    def write_seconds(self) -> float: ...

def encode_merged_arrays(leaves: TrainedLevel, parents: MergedLevel, children: Buffer,
                         output_dir: str, lod_base: float,
                         compression: Compression = Compression.Gz) -> None: ...

def encode_merged_archive(leaves: TrainedLevel, parents: MergedLevel, children: Buffer,
                          output_file: str, lod_base: float,
                          compression: Compression = Compression.Gz) -> EncodeTimings: ...
